import "./globals.css";


export const metadata = {
  title: "e engine",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="h-screen border-2 border-pink-400 bg-gray-300">
      <body className="h-screen">
        {children}
      </body>
    </html>
  );
}
